messaging:
  topic:
    eventPattern: __keyevent@*
    destination: /topic/events
  websocket-endpoint: /betvictor-websocket

server:
  port: 9000

info:
  app:
    version: ${version}

logging:
  level:
    bvtech: DEBUG