version: '3.1'

services:

  actionmonitor:
    image: betvictor-action-monitor
    hostname: actionmonitor
    container_name: betvictor_actionmonitor
    restart: always
    ports:
      - 9000:9000
    environment:
      - SPRING_REDIS_HOST=redis

  client:
    image: betvictor-client
    container_name: betvictor_client
    restart: always
    ports:
      - 8080:8080
    environment:
      - NOTIFICATIONSERVER_URL=http://${HOSTNAME}:9000
