version: '3.1'

services:

  redis:
    image: redis:4.0.10-alpine
    container_name: actionmonitor_redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ${PWD}/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  commander:
    image: rediscommander/redis-commander:latest
    container_name: actionmonitor_commander
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081
    depends_on:
      - redis
